src/ReclameAquiDoTrader.UI/Controllers/AssinantesController.cs
using Microsoft.AspNetCore.Mvc;
using ReclameAquiDoTrader.Business.Core.Communication.Notificacoes;
using ReclameAquiDoTrader.Business.Interfaces.Repository;
using ReclameAquiDoTrader.UI.ViewModels.AssinantesViewModels;
using System.Collections.Generic;
using System.Linq;

namespace ReclameAquiDoTrader.UI.Controllers
{
    public class AssinantesController : MainController
    {
        private readonly IAssinanteRepository _assinanteRepository;

        public AssinantesController(IAssinanteRepository assinanteRepository,
                                    INotificador notificador) : base(notificador)
        {
            _assinanteRepository = assinanteRepository;
        }

        public IActionResult Index()
        {
            var viewModel = new List<DetalhesAssinantesViewModel>();

            var assinantes = _assinanteRepository.Listar().OrderByDescending(m => m.CriadoAs);
            foreach (var assinante in assinantes)
                viewModel.Add(new DetalhesAssinantesViewModel()
                {
                    CriadoAs = assinante.CriadoAs,
                    Id = assinante.Id,
                    Telefone = assinante.Whatsapp
                });

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Detalhes(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();

            var viewModel = new DetalhesAssinantesViewModel();

            var assinante = _assinanteRepository.ObterPorId(id);
            if (assinante == null)
            {
                NotificarErro("Detalhes", "Assinante não encontrado");
                return CustomResponse();
            }

            viewModel.Id = assinante.Id;
            viewModel.CriadoAs = assinante.CriadoAs;
            viewModel.Telefone = assinante.Whatsapp;

            return PartialView("_Detalhes", viewModel);
        }
    }
}

src/ReclameAquiDoTrader.UI/Views/Assinantes/Index.cshtml
@model List<ReclameAquiDoTrader.UI.ViewModels.AssinantesViewModels.DetalhesAssinantesViewModel>
@using ReclameAquiDoTrader.UI.Extensions;

@{
    ViewData["Title"] = "Listar Assinantes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/lib/select2/css/select2_site.min.css" rel="stylesheet">
<link href="~/lib/select2/css/select2-bootstrap4.min.css" rel="stylesheet">
<link href="~/lib/bootstrap/dist/css/bootstrap-tagsinput.css" rel="stylesheet">
<link rel="stylesheet" href="~/lib/footable/css/footable.bootstrap.min.css" />

<style>
    .footable-filtering-search .input-group-btn {
        display: none;
    }

    .footable-filtering-search {
        width: 100% !important;
    }

        .footable-filtering-search .input-group {
            width: 100% !important;
        }

    .texto-sucesso {
        color: #28a745;
    }
</style>

<div class="ibox" id="lista_asinantes">
    <div class="ibox-title">
        <h1>@ViewData["Title"]</h1>
    </div>

    <div class="ibox-content">
        <div class="ibox-content">

            <table id="tabela-assinantes"
                   class="footable table"
                   data-paging-count-format="{CP} de {TP} páginas"
                   data-paging="true"
                   data-sorting="true"
                   data-filtering="true"
                   data-paging-limit="3"
                   data-filter-placeholder="Pesquise aqui...">
                <thead>
                    <tr>
                        <th>WhatsApp</th>
                        <th data-breakpoints="xs">Data Cadastro</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var assinante in Model)
                    {
                        <tr>
                            <td>
                                <div>
                                    @if (assinante.Telefone != null)
                                    {
                                        <span>@assinante.Telefone.FormataTelefone()</span>
                                        <br />
                                    }
                                </div>
                            </td>
                            <td>
                                <div>
                                    @assinante.CriadoAs.FormataData()
                                </div>
                            </td>
                            <td>
                                <div class="d-inline-flex">
                                    <a asp-controller="Assinantes" asp-action="Detalhes" asp-route-id="@assinante.Id"
                                       type="button" class="btn btn-outline btn-link text-warning abre-modal-generico" style="min-width: 28px; cursor: pointer;"
                                       data-toggle="tooltip" title="Detalhes">
                                        <i class="fa fa-search" data-toggle="tooltip"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>

<script src="~/lib/footable/js/footable.3.6.1.min.js"></script>

@section Scripts
 {

    <script>
        $('[data-toggle="tooltip"]').tooltip();

        $(document).ready(function () {
            $('.footable').footable();
        });
    </script>
}

src/ReclameAquiDoTrader.UI/Views/Assinantes/_Detalhes.cshtml
@using ReclameAquiDoTrader.UI.Extensions;
@model ReclameAquiDoTrader.UI.ViewModels.AssinantesViewModels.DetalhesAssinantesViewModel

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
    <h4 class="modal-title">Detalhes do Assinante</h4>
    @*<small class="font-bold">Cadastre um novo mentor.</small>*@
</div>

<div class="modal-body bg-white">
    <div class="row pb-3">
        <div class="col-sm mt-3">
            <h3>@Html.DisplayNameFor(model => model.Telefone)</h3>
            <span>@Model.Telefone.FormataTelefone()</span>
            <br />
        </div>
        <div class="col-sm mt-3">
            <h3>Data do Cadastro</h3>
            <span>@Model.CriadoAs.FormataData()</span>
            <br />
        </div>
    </div>
</div>

<div class="modal-footer" style="justify-content:left;">
    <button type="button" class="btn btn-info" data-dismiss="modal">Fechar</button>
</div>