src/ReclameAquiDoTrader.UI/Controllers/PesquisaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ReclameAquiDoTrader.Business.Aggregates;
using ReclameAquiDoTrader.Business.Core.Communication.Notificacoes;
using ReclameAquiDoTrader.Business.Core.DomainObjects;
using ReclameAquiDoTrader.Business.Interfaces.Repository;
using ReclameAquiDoTrader.UI.Extensions;
using ReclameAquiDoTrader.UI.ViewModels.PesquisaViewModels;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ReclameAquiDoTrader.UI.Controllers
{
    [AllowAnonymous]
    public class PesquisaController : MainController
    {
        private readonly IAvaliacaoRepository _avaliacaoRepository;
        private readonly IMentorRepository _mentorRepository;
        private readonly IAssinanteRepository _assinanteRepository;

        public PesquisaController(
                                IAssinanteRepository assinanteRepository,
                                IAvaliacaoRepository avaliacaoRepository,
                                IMentorRepository mentorRepository,
                                INotificador notificador) : base(notificador)
        {
            _avaliacaoRepository = avaliacaoRepository;
            _mentorRepository = mentorRepository;
            _assinanteRepository = assinanteRepository;
        }

        public IActionResult Index()
        {
            var avaliacoes = _avaliacaoRepository.Listar().Where(x => x.Inativo == false);
            var mentores = _mentorRepository.Listar();
            var viewModel = new AvaliacaoParaPesquisaViewModel();
            foreach (var avaliacao in avaliacoes)
            {
                var areasAtuacao = new List<string>();

                var mentor = mentores.FirstOrDefault(m => m.Id == avaliacao.MentorId);
                if (mentor == null)
                    continue;

                if (mentor.AreasDeAtuacao != null)
                    areasAtuacao = mentor.AreasDeAtuacao.ToList();

                viewModel.Avaliacoes.Add(new AvaliacaoParaPesquisaItemViewModel
                {
                    AvaliacaoId = avaliacao.Id,
                    Positivo = avaliacao.Positivo,
                    Respondido = avaliacao.Respondido,
                    CriadoAs = avaliacao.CriadoAs,
                    Texto = avaliacao.Texto,
                    RedesSociais = avaliacao.RedesSociais?.Lista?.Select(r =>
                        new RedeSocialViewModel()
                        {
                            Tipo = r.Tipo,
                            Url = r.Url,
                            Usuario = r.Usuario
                        }).ToList(),
                    Mentor = new MentorViewModel()
                    {
                        AreasDeAtuacao = areasAtuacao,
                        MentorId = mentor.Id,
                        Nome = mentor.Nome,
                        RedesSociais = mentor.RedesSociais?.Lista?.Select(r =>
                        new RedeSocialViewModel()
                        {
                            Tipo = r.Tipo,
                            Url = r.Url,
                            Usuario = r.Usuario
                        }).ToList(),
                    }
                });
            }
            return View(viewModel);
        }

        public IActionResult Newsletter()
        {
            return PartialView("_ModalNewsletter", new AssinarNewsletterViewModel());
        }

        public IActionResult EntendaAvalicoesNegativas()
        {
            return PartialView("_ModalEntendaAvaliacoesNegativas");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AssinarNewsletter([FromBody] AssinarNewsletterViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return CustomResponse(ModelState);

            try
            {
                var assinante = new Assinante(viewModel.Whatsapp.SomenteNumeros());
                _assinanteRepository.Adicionar(assinante);
                _assinanteRepository.SalvarAlteracoes();
                Response.Cookies.Append("Assinante", "1");
            }
            catch (DomainException dex)
            {
                NotificarErro("", dex.Message);
            }
            catch (Exception)
            {
                NotificarErro("", "Desculpe, tivemos um problema. Por favor, tente novamente em alguns instantes");
            }
            return CustomResponse();
        }
    }
}

src/ReclameAquiDoTrader.UI/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="float-right">
        Desenvolvido por 
        <a href="https://www.linkedin.com/in/elvissouza/" target="_blank">
            Elvis Souza
        </a> e
        <a href="https://www.linkedin.com/in/diego-galante/" target="_blank">
            Diego Galante
        </a>
    </div>
    <div>
        <strong>Copyright</strong> Reclame Aqui do Trader &copy; 2018 - @DateTime.UtcNow.Year
    </div>
</div>

src/ReclameAquiDoTrader.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RADT Admin</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Cache-control" content="no-cache">

    <link rel="shortcut icon" href="~/img/fav-icon.png" type="image/x-icon">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <link rel="stylesheet" href="~/css/site.min.css" />

</head>
<body>
    <script src="~/js/site.min.js"></script>

    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script src="~/lib/jquery/jquery.mask.js"></script>

    @RenderSection("scripts", required: false)

    <div id="wrapper" class="@Html.PageClass()">
        <partial name="_Navigation" />
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">
            <partial name="_TopNavbar" />
            <div class="wrapper-content">
                @RenderBody()
            </div>
            <partial name="_Footer" />
        </div>
    </div>

    <partial name="_ModalGenerico" />

</body>
</html>

src/ReclameAquiDoTrader.UI/Views/Shared/_ModalGenerico.cshtml
<div id="modalGenerico" class="modal inmodal fade in" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
        </div>
    </div>
</div>

src/ReclameAquiDoTrader.UI/Views/Shared/_Navigation.cshtml
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span style="color: aliceblue;" class="block m-t-xs font-bold">@User.Identity.Name</span>
                </div>
                <div class="logo-element">
                    RADT
                </div>
            </li>
            <li class="@Html.IsSelected(controller: "Dashboard", action: "Index")">
                <a href="@Url.Action("Index", "Dashboard")"><i class="fa fa-dashboard"></i> <span class="nav-label">Dashboard</span></a>
            </li>
            <li class="@Html.IsSelected(controller: "Avaliacoes", action: "Index")">
                <a href="#"><i class="fa fa-comments-o"></i> <span class="nav-label">Avaliações</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="@Url.Action("Index", "Avaliacoes")"><i class="fa fa-comments"></i>Todas</a></li>
                    <li><a href="@Url.Action("EmAndamento", "Avaliacoes")"><i class="fa fa-clock-o"></i>Em Andamento</a></li>
                    <li><a href="@Url.Action("PendentesPublicacao", "Avaliacoes")"><i class="fa fa-bullhorn"></i>Para Publicar</a></li>
                    <li><a href="@Url.Action("Publicadas", "Avaliacoes")"><i class="fa fa-check"></i>Publicadas</a></li>
                </ul>
            </li>
            <li class="@Html.IsSelected(controller: "Mentores", action: "index")">
                <a href="@Url.Action("Index", "Mentores")"><i class="fa fa-graduation-cap"></i> <span class="nav-label">Mentores</span></a>
            </li>
            <li class="@Html.IsSelected(controller: "Assinantes", action: "index")">
                <a href="@Url.Action("Index", "Assinantes")"><i class="fa fa-users"></i> <span class="nav-label">Assinantes</span></a>
            </li>
            <li class="landing_link">
                <a href="@Url.Action("Index", "Pesquisa")" target="_blank"><i class="fa fa-star"></i> <span class="nav-label">Site</span></a>
            </li>
        </ul>
    </div>
</nav>

src/ReclameAquiDoTrader.UI/Views/Shared/_TopNavbar.cshtml
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a asp-controller="Account" asp-action="Sair" >
                    <i class="fa fa-sign-out"></i> Sair
                </a>
            </li>
        </ul>
    </nav>
</div>